M.AutoInit();
var elem = document.getElementById("input-devices-selector");
var instance = M.FormSelect.getInstance(elem);
console.log(instance.input);
var node = document.createElement("option");
node.value = "4";
var textNode = document.createTextNode("Meme!");
node.appendChild(textNode);
elem.appendChild(node);
instance.destroy();
console.log(elem);
M.FormSelect.init(elem, null);